## Function

In [ ]:
#Contoh sederhana menghitung luas persegi
def detailPersegi(p,l):
    luas = p * l
    keliling = 2*(p+l)
    return luas,keliling

detailPersegi(2,4)
print(f"Detail persegi adalah: {detailPersegi}")
print(f"Luas persegi adalah: {detailPersegi(2,4)[0]}")
print(f"Keliling persegi adalah: {detailPersegi(2,4)[1]}")

#output dari return yang lebih dari 1 akan dijadikan tuple

In [ ]:
a = 4
a

In [ ]:
#Variabel Length Arguments --> untuk kalau parameterny ada banyak
# daripada contohFunction(a,b,c,d,e) -- mending contohFunction(a,*parametNameBCDE)
#*parametABCDE akan mengeluarkan hasil berupa tuples

def kelilingSegi5Sembarang(a,*aspekLain):
    hasilTambah = 0
    for item in(aspekLain):
        hasilTambah += item
    keliling = a + hasilTambah
    return keliling

print(kelilingSegi5Sembarang(1,2,3,4,5))



In [ ]:
def person_car(total_data,**keywordArgs) :
#duaAsterisk seperti **keywordArgs akan membutuhkan argumen berupa dictionaries
    print('Total Data :',total_data)
    for key,value in keywordArgs.items():
        print('Person :',key)
        print('Car: ',value)
        print('')

person_car(3, jimmy ='chevrolet',frank = 'ford',tina = 'honda')

In [ ]:
kwargs = {
    'jimmy' : 'chevrolet',
    'frank' : 'ford',
    'tina' : 'honda'
}
print(kwargs.items())
#ini adalah hasil dari print dictionary.items()

## Lambda

In [ ]:
#Menggunakan lambda sama seperti menggunaan function, misalnya pada contoh
penjumlahan = lambda a,b : a+b
print(penjumlahan(10,5))

#Hasil di atas akan sama hasilnya seperti hasil di bawah
def penjumlahanMath(a,b):
    return a+b
print("Hasil penjumlahan a+b menggunakan function adalah: ",penjumlahanMath(10,5))

In [ ]:
# sum = lambda arg1, *arg2 : arg1 + arg2 -- tidak bisa, karena operasi setelah titik dua harus tipe data yang sama
# yang bisa menggunakan tuple *arg2 hanya seperti ini
sum = lambda arg1,*arg2 : arg1 + arg2[0]
print(f"Hasil penjumlahan adalah {sum(10,20,30,40)}")

In [ ]:
#Declate global variabel
total =0

def sum(arg1,arg2):
    total = arg1+arg2
    print("Inside the function local total :",total)
    return total

print("Outside the function global - before:",total)
total = sum(10,20)
print("Outside the function global - after:",total)


## Package
- Mengimport dari file / data lain

In [ ]:
import importlib
import person
import person_tanpa_return
importlib.reload(person)
importlib.reload(person_tanpa_return)
#jika ada data baru di person , bs diupdate pakai :
#importlib.reload(person) -- tapi harus inisiasi import importlib dulu di paling atas
print(person.nama)
print(person_tanpa_return.devices)
person_tanpa_return.display('Mizu')
print(person_tanpa_return.nama)





In [ ]:
#Bisa memanggil variabel/function dalam modul scr spesifik dengan fungsi 'from' , agar tidak perlu panggil nama modul lagi
from person import nama
from person_tanpa_return import display
display('Chizuuu') 
print(nama)

## Package
- Import dari folder lain yang ada macem" .py nya


In [ ]:
#Contoh penggunaaan package 
# import pkg.file1, pkg.file2
# print(pkg.file1.hewan)
# print(pkg.file2.tumbuhan)

# bisa juga seperti ini
# from pkg import file1,file2
# print(file1.hewan)
# print(file2.tumbuhan)


In [ ]:
import sys
print(sys.path)

## Numpy

In [1]:
import numpy as np

In [ ]:
tinggi = [1.7,1.8,1.9,1.1,1.11,1.12]
berat = [60.5,61.5,62.5,63.5,64.5,65.6]

# berat / tinggi -- pembagian array scr langsung spt ini tidak bisa

# maka perlu menggunakan numpy.array untuk membagi list spt di atas
np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

print(np_tinggi/np_berat)

In [ ]:
#numpy.arange -- untuk membuat arraylist
np.arange(5)

In [ ]:
np.arange(3,10,2) #(start,batas akhir - 1,loncat)
print(np.arange(3,10,2))

In [ ]:
#numpy append
arr = np.array([1,2,3,4])
arr_new = np.append(arr,[7,8,9]) #ada fungsi append yang bisa digunakan
print(arr_new)

In [ ]:
#numpy delete
np.delete(arr_new,3) #fungsi delete disini menghapus berdasarkan index
print(arr_new)

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

In [ ]:
arr.ndim #jumlah dimensi

In [ ]:
arr.shape 

## 2-D / matriks

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr.ndim

2

In [5]:
arr.shape

(2, 4)

In [6]:
arr.size

8

## 3 Dimensi

In [7]:
arr = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]]


In [8]:
arr.ndim

3

In [9]:
arr.shape #mewakili masing" dimensi ada berapa 

(1, 2, 4)

In [10]:
arr.size #ada berapa elemen di dalamnya

8

In [117]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [118]:
#misal mau buat matriks dengan reshape
matriks = arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [119]:
matriks = arr.reshape(2,3)
print(matriks)

[[0 1 2]
 [3 4 5]]


In [120]:
matriks = arr.reshape(6,1) # reshape(sumbu x,sumbu y)
print(matriks)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [121]:
matriks.shape

(6, 1)

In [122]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [123]:
a.shape

(6,)

In [124]:
a2 = a[np.newaxis]
# a2 = a[np.newaxis, :] # sama seperti di atas , axisnya tadi (6,) jadi (1,6)
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [125]:
a3 = a[:, np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [126]:
a_e = np.expand_dims(a, axis=1)
a_e.shape
print(a_e)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [127]:
a_e2 = np.expand_dims(a, axis=0)
a_e2.shape
print(a_e2)

[[1 2 3 4 5 6]]


## soal

In [128]:
arr = np.array([1,2,7,4,10,5])
print(arr[2:6])


[ 7  4 10  5]


In [129]:
arr = np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])


[7 5]


In [130]:
arr = np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [131]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[0,2])

3


In [132]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[0,1:3]) #di baris ke 0 , di index ke 1 sampai dibawah 3(index ke 2)

[2 3]


In [133]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[2:4,2]) 

[11]


In [134]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[2:3,3]) 

[12]


In [10]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[1:2,3]) 

[8]


In [11]:
arr = np.array([[1,2,3,4,8,10],
                [5,6,7,8,7,10],
                [9,10,11,12,11,12]])
print(arr[1:2,3]) 

[8]


In [12]:
arr = np.array([[1,2,3,4,8,10],
                [5,6,7,8,7,10],
                [9,10,11,12,11,12]])
print(arr[:4:2,2]) 

[ 3 11]


In [13]:
arr = np.array([[1,2,3,4,8,10],
                [5,6,7,8,7,10],
                [9,10,11,12,11,12]])
print(arr[1:2,2:3]) 

[[7]]


In [14]:
arr = np.array([[1,2,3,4,8,10],
                [5,6,7,8,7,10],
                [9,10,11,12,11,12]])
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]


In [15]:
#cek dimensi di atas
arr_cek = arr[arr>=3]
arr_cek.ndim

1

In [16]:
a_1 = np.array([[1,1],[2,2]])

a_2 = np.array([[3,3],[4,4]])

np.vstack((a_1,a_2))



array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [17]:
a_1 = np.array([[1,1],[2,2]])

a_2 = np.array([[3,3],[4,4]])

np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [18]:
arr_new = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])

new_arr = arr_new.reshape(2,3,-1) #unknown dimension
print(new_arr.shape)
print(new_arr)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [19]:
arr_new = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])

new_arr = arr_new.reshape(2,2,3) #2 dimension
print(new_arr.shape)
print(new_arr)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
### Concatenate Array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [29]:
### Concatenate array dengan axis = 1 -- tidak bisa karena hanya 1 dimensi
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate([arr1,arr2],axis=1)
print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [30]:
### Concatenate array dengan axis = 0 - 1 dimensi hanya bisa axis = 0 atau penjumlahan kebawah
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate([arr1,arr2],axis=0)
print(arr)

[1 2 3 4 5 6]


In [28]:
### Concatenate array dengan axis
arr1 = np.array([[1,2,3],
                [1,2,3]])
arr2 = np.array([[4,5,6],
                [4,5,6]])
arr = np.concatenate([arr1,arr2],axis=0)
print(arr)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


##### ada materi numpy --> ravel, flatten